import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import PostsContext from "../components/Context/PostsContext";
import { IPostsItem } from "@interfaces/Posts";
import { IUser } from "@interfaces/Users";
import { getData } from "@utils/sharedFncs";
import { API_URL } from "@config/api";
import { IComment } from "@interfaces/Comments";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const posts: IPostsItem[] = await getData(`${API_URL}/posts`);
  const users: IUser[] = await getData(`${API_URL}/users`);
  const comments: IComment[] = await getData(`${API_URL}/comments`);

  return (
    <html lang="en">
      <body className={inter.className}>
        <PostsContext users={users} posts={posts} comments={comments}>
          {children}
        </PostsContext>
      </body>
    </html>
  );
}
